// src/lib/rbacPermissions.ts
import prisma from "@/lib/prisma";
import { PERMISSIONS, PERMISSION_DEFINITIONS } from "@/rbac/permissions";
export { PERMISSIONS, PERMISSION_DEFINITIONS } from "@/rbac/permissions";
export type { PermissionDefinition } from "@/rbac/permissions";

/**
 * Loads all permissions dynamically from the database.
 */
export async function getAllPermissionsFromDb(): Promise<{
  id?: number;
  category: string;
  key: string;
  description: string | null;
}[]> {
  try {
    const permissions = await prisma.permission.findMany({
      orderBy: [{ category: "asc" }, { key: "asc" }],
    });
    return permissions.map((p) => ({
      id: p.id,
      category: p.category || "General",
      key: p.key,
      description: p.description,
    }));
  } catch (error) {
    console.error("Error loading permissions dynamically from database:", error);
    return [];
  }
}

/**
 * Backwards-compatible dictionary of permission keys mapping to canonical definitions.
 * Corresponds to keys stored in the permissions database table.
 */
export const PERMISSION_KEYS = {
  // Dashboard
  DASHBOARD_VIEW: PERMISSIONS.DASHBOARD.VIEW,

  // Employee
  EMPLOYEE_VIEW: PERMISSIONS.EMPLOYEE.VIEW,
  EMPLOYEE_CREATE: PERMISSIONS.EMPLOYEE.CREATE,
  EMPLOYEE_EDIT: PERMISSIONS.EMPLOYEE.EDIT,
  EMPLOYEE_DELETE: PERMISSIONS.EMPLOYEE.DELETE,
  EMPLOYEE_VERIFY: PERMISSIONS.EMPLOYEE.VERIFY,
  EMPLOYEE_SEND_CREDENTIALS: PERMISSIONS.EMPLOYEE.SEND_CREDENTIALS,
  EMPLOYEE_RESET_PASSWORD: PERMISSIONS.EMPLOYEE.RESET_PASSWORD,
  EMPLOYEE_EXPORT: PERMISSIONS.EMPLOYEE.EXPORT,

  // Attendance
  ATTENDANCE_VIEW: PERMISSIONS.ATTENDANCE.VIEW,
  ATTENDANCE_EDIT: PERMISSIONS.ATTENDANCE.EDIT,
  ATTENDANCE_ANALYTICS: PERMISSIONS.ATTENDANCE.ANALYTICS,
  ATTENDANCE_MY: PERMISSIONS.ATTENDANCE.MY,
  ATTENDANCE_REGULARIZE: PERMISSIONS.ATTENDANCE.REGULARIZE,
  ATTENDANCE_REGULARIZE_APPROVE: PERMISSIONS.ATTENDANCE.REGULARIZE_APPROVE,

  // Leave
  LEAVE_VIEW: PERMISSIONS.LEAVE.VIEW,
  LEAVE_VIEW_PENDING: PERMISSIONS.LEAVE.VIEW_PENDING,
  LEAVE_VIEW_HISTORY: PERMISSIONS.LEAVE.VIEW_HISTORY,
  LEAVE_APPROVE: PERMISSIONS.LEAVE.APPROVE,
  LEAVE_CANCEL: PERMISSIONS.LEAVE.CANCEL,
  LEAVE_REQUEST: PERMISSIONS.LEAVE.REQUEST,
  LEAVE_VIEW_OWN: PERMISSIONS.LEAVE.VIEW_OWN,
  LEAVE_VIEW_LEAVE_TYPES: PERMISSIONS.LEAVE.VIEW_LEAVE_TYPES,
  LEAVE_CREATE_TYPE: PERMISSIONS.LEAVE.CREATE_TYPE,
  LEAVE_EDIT_TYPE: PERMISSIONS.LEAVE.EDIT_TYPE,
  LEAVE_DELETE_TYPE: PERMISSIONS.LEAVE.DELETE_TYPE,

  // Payroll
  PAYROLL_VIEW: PERMISSIONS.PAYROLL.VIEW,
  PAYROLL_GENERATE: PERMISSIONS.PAYROLL.GENERATE,
  PAYROLL_EDIT: PERMISSIONS.PAYROLL.EDIT,
  PAYSLIP_VIEW: PERMISSIONS.PAYSLIP.VIEW,

  // Recruitment
  RECRUITMENT_VIEW: PERMISSIONS.RECRUITMENT.VIEW,
  RECRUITMENT_CREATE: PERMISSIONS.RECRUITMENT.CREATE,
  RECRUITMENT_EDIT: PERMISSIONS.RECRUITMENT.EDIT,
  RECRUITMENT_DELETE: PERMISSIONS.RECRUITMENT.DELETE,
  RECRUITMENT_UPDATE_STATUS: PERMISSIONS.RECRUITMENT.UPDATE_STATUS,
  RECRUITMENT_SEND_MAIL: PERMISSIONS.RECRUITMENT.SEND_MAIL,
  RECRUITMENT_CONVERT_EMPLOYEE: PERMISSIONS.RECRUITMENT.CONVERT_EMPLOYEE,
  RECRUITMENT_APPLICATIONS_VIEW: PERMISSIONS.RECRUITMENT.APPLICATIONS_VIEW,
  RECRUITMENT_ANALYTICS: PERMISSIONS.RECRUITMENT.ANALYTICS,
 
  // JD
  JD_VIEW: PERMISSIONS.JD.VIEW,
  JD_CREATE: PERMISSIONS.JD.CREATE,
  JD_PUBLISH: PERMISSIONS.JD.PUBLISH,
  JD_EDIT: PERMISSIONS.JD.EDIT,
  JD_CLOSE: PERMISSIONS.JD.CLOSE,
  JD_ANALYZE: PERMISSIONS.JD.ANALYZE,

  // Job Application
  JOB_APPLICATION_VIEW: PERMISSIONS.JOB_APPLICATION.VIEW,
  JOB_APPLICATION_PARSE: PERMISSIONS.JOB_APPLICATION.PARSE,
  JOB_APPLICATION_SHORTLIST: PERMISSIONS.JOB_APPLICATION.SHORTLIST,
  JOB_APPLICATION_REJECT: PERMISSIONS.JOB_APPLICATION.REJECT,
  JOB_APPLICATION_SCHEDULE: PERMISSIONS.JOB_APPLICATION.SCHEDULE,

  // Resume
  RESUME_PARSE: PERMISSIONS.RESUME.PARSE,
  RESUME_DOWNLOAD: PERMISSIONS.RESUME.DOWNLOAD,

  // Candidate
  CANDIDATE_RANK_VIEW: PERMISSIONS.CANDIDATE.RANK_VIEW,
  CANDIDATE_COMPATIBILITY_VIEW: PERMISSIONS.CANDIDATE.COMPATIBILITY_VIEW,

  // Compliance
  COMPLIANCE_VIEW: PERMISSIONS.COMPLIANCE.VIEW,
  COMPLIANCE_VIEW_DOCUMENTS: PERMISSIONS.COMPLIANCE.VIEW_DOCUMENTS,
  COMPLIANCE_REQUEST_RESUBMISSION: PERMISSIONS.COMPLIANCE.REQUEST_RESUBMISSION,

  // Task
  TASK_VIEW: PERMISSIONS.TASK.VIEW,
  TASK_CREATE: PERMISSIONS.TASK.CREATE,
  TASK_EDIT: PERMISSIONS.TASK.EDIT,
  TASK_DELETE: PERMISSIONS.TASK.DELETE,
  TASK_MY: PERMISSIONS.TASK.MY,
  TASK_UPDATE_STATUS: PERMISSIONS.TASK.UPDATE_STATUS,

  // Reports
  REPORT_VIEW: PERMISSIONS.REPORT.VIEW,
  REPORT_VIEW_OWN: PERMISSIONS.REPORT.VIEW_OWN,
  REPORT_SUBMIT: PERMISSIONS.REPORT.SUBMIT,

  // Calendar
  CALENDAR_VIEW: PERMISSIONS.CALENDAR.VIEW,
  CALENDAR_MANAGE: PERMISSIONS.CALENDAR.MANAGE,
  CALENDAR_CREATE: PERMISSIONS.CALENDAR.CREATE,
  CALENDAR_EDIT: PERMISSIONS.CALENDAR.EDIT,
  CALENDAR_DELETE: PERMISSIONS.CALENDAR.DELETE,
  CALENDAR_DOWNLOAD_HOLIDAYS: PERMISSIONS.CALENDAR.DOWNLOAD_HOLIDAYS,
  CALENDAR_DOWNLOAD_EVENTS: PERMISSIONS.CALENDAR.DOWNLOAD_EVENTS,

  // Customer Connect
  CUSTOMER_VIEW: PERMISSIONS.CUSTOMER.VIEW,
  CUSTOMER_DELETE: PERMISSIONS.CUSTOMER.DELETE,

  // Notifications
  NOTIFICATION_VIEW: PERMISSIONS.NOTIFICATION.VIEW,

  // Documents
  DOCUMENT_SUBMIT: PERMISSIONS.DOCUMENT.SUBMIT,
  DOCUMENT_VIEW_OWN: PERMISSIONS.DOCUMENT.VIEW_OWN,

  // Settings
  SETTINGS_PROFILE: PERMISSIONS.SETTINGS.PROFILE,
  SETTINGS_CHANGE_PASSWORD: PERMISSIONS.SETTINGS.CHANGE_PASSWORD,
  SETTINGS_POSITION_VIEW: PERMISSIONS.SETTINGS.POSITION_VIEW,
  SETTINGS_POSITION_MANAGE: PERMISSIONS.SETTINGS.POSITION_MANAGE,
  SETTINGS_POSITION_CREATE: PERMISSIONS.SETTINGS.POSITION_CREATE,
  SETTINGS_POSITION_EDIT: PERMISSIONS.SETTINGS.POSITION_EDIT,
  SETTINGS_POSITION_DELETE: PERMISSIONS.SETTINGS.POSITION_DELETE,
  SETTINGS_POSITION_ASSIGN: PERMISSIONS.SETTINGS.POSITION_ASSIGN,
  SETTINGS_DEPARTMENT_VIEW: PERMISSIONS.SETTINGS.DEPARTMENT_VIEW,
  SETTINGS_DEPARTMENT_CREATE: PERMISSIONS.SETTINGS.DEPARTMENT_CREATE,
  SETTINGS_DEPARTMENT_EDIT: PERMISSIONS.SETTINGS.DEPARTMENT_EDIT,
  SETTINGS_DEPARTMENT_DELETE: PERMISSIONS.SETTINGS.DEPARTMENT_DELETE,
  SETTINGS_ROLE_VIEW: PERMISSIONS.SETTINGS.ROLE_VIEW,
  SETTINGS_ROLE_CREATE: PERMISSIONS.SETTINGS.ROLE_CREATE,
  SETTINGS_ROLE_EDIT: PERMISSIONS.SETTINGS.ROLE_EDIT,
  SETTINGS_ROLE_DELETE: PERMISSIONS.SETTINGS.ROLE_DELETE,
  SETTINGS_EMPLOYEE_TYPES_MANAGE: PERMISSIONS.SETTINGS.EMPLOYEE_TYPES_MANAGE,
  SETTINGS_BOT: PERMISSIONS.SETTINGS.BOT,
  SETTINGS_BOT_UPLOAD: PERMISSIONS.SETTINGS.BOT_UPLOAD,
  SETTINGS_BOT_DELETE: PERMISSIONS.SETTINGS.BOT_DELETE,
  SETTINGS_MANAGE: PERMISSIONS.SETTINGS.MANAGE,

  // Canonical backwards-compatible aliases
  BOT_SETTINGS: PERMISSIONS.SETTINGS.BOT,
  POSITION_VIEW: PERMISSIONS.SETTINGS.POSITION_VIEW,
  POSITION_MANAGE: PERMISSIONS.SETTINGS.POSITION_MANAGE,

  // RBAC System Management
  RBAC_PERMISSION_VIEW: PERMISSIONS.RBAC.PERMISSION_VIEW,
  RBAC_ROLE_MANAGE: PERMISSIONS.RBAC.ROLE_MANAGE,
  RBAC_ROLE_ASSIGN: PERMISSIONS.RBAC.ROLE_ASSIGN,
  RBAC_ROLE_PERMISSION_ASSIGN: PERMISSIONS.RBAC.ROLE_PERMISSION_ASSIGN,
} as const;
