export const SESSION_TIMEOUT_MS = 5 * 60 * 1000;
export const IDLE_TIMEOUT_MS = 5 * 60 * 1000;
export const PROMPT_BEFORE_MS = 60 * 1000;
export const ACTIVITY_THROTTLE_MS = 30 * 1000;
export const JWT_EXPIRY_MS = 12 * 60 * 60 * 1000;

export const SESSION_CONFIG = {
  TIMEOUT: SESSION_TIMEOUT_MS,
  JWT_EXPIRY: JWT_EXPIRY_MS,
  WARNING_OFFSET: PROMPT_BEFORE_MS,
  IDLE_TIMEOUT: IDLE_TIMEOUT_MS,
  ACTIVITY_THROTTLE: ACTIVITY_THROTTLE_MS,
  SESSION_TIMEOUT_MS,
};
